application: sc-intelligence
version: 1
runtime: go
api_version: go1

automatic_scaling:
  max_idle_instances: 1
  min_pending_latency: 500ms
  max_pending_latency: 5s
  max_concurrent_requests: 100

handlers:
- url: /favicon.ico
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /static
  static_dir: static

- url: /task/.*
  login: admin
  script: _go_app
  secure: always

- url: /admin/.*
  login: admin
  script: _go_app
  secure: always

- url: /.*
  script: _go_app
  secure: always
